# Generated by Django 3.2.3 on 2021-06-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeJumpers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='videos',
            new_name='Video',
        ),
    ]
